version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./var/www/:/var/www/
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./var/www/:/var/www/
    working_dir: /var/www/harbors
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: harbors
      MYSQL_USER: harbors
      MYSQL_PASSWORD: harbors1234
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./database:/var/lib/mysql
